### GET / route
GET http://localhost:3000
Content-Type: application/json

### GET users
GET http://localhost:3000/users
Content-Type: application/json

### GET one user
GET http://localhost:3000/user1
Content-Type: application/json

### POST new user
POST http://localhost:3000/users
Content-Type: application/json


### DELETE user by id
DELETE  http://localhost:3000/users
Content-Type: application/json

### PATCH user by id
PATCH http://localhost:3000/users
Content-Type: application/json

### SEND logged user
POST http://localhost:3000/users/login
Content-Type: application/json

### POST stepdata
POST  http://localhost:3000/stepDataAdd
Content-Type: application/json


### GET stepdata
GET  http://localhost:3000/stepdataFill/4
Content-Type: application/json

### PATCH stepdata
PATCH  http://localhost:3000/stepdataUpdate/1
Content-Type: application/json

{
    "userID": "4",
    "stepCount": "335",
    "date": "2025-09-04",
    "id": 1
}

### DELETE stepdata by id
DELETE  http://localhost:3000/stepdataDelete/1
Content-Type: application/json

### DELETE stepdata by userID
DELETE  http://localhost:3000/stepdataDeleteAll/:4
Content-Type: application/json